name: PhpUnit Testing
on: [push]
jobs:
  PhpUnit-Tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Test Run 
        working-directory: tests
        shell: bash
        uses: actions/checkout@v2
        run: phpunit
