name: PhpUnit Staging Testing
on: 
  push:
    branches:
      - staging
jobs:
  PhpUnit-Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Run 
        working-directory: tests
        shell: bash
        run: phpunit .
