name: PhpUnit Testing
on: [push]
jobs:
  PhpUnit-Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Run 
        working-directory: tests
        shell: bash
        run: phpunit
